name: Provision or update core infrastructure on Azure
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read
    
env:
  AZURE_RESOURCE_GROUP: xeniel

jobs:
  build:    
    runs-on: ubuntu-latest

    
    steps:      
      - uses: actions/checkout@v2
      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false

      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: az group list -o table

#      - name: Deploy Azure Resource Manager (ARM) Template
#        uses: Azure/arm-deploy@main
#        with:
#          scope: resourcegroup
#          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
#          template: ./Infrastructure/main.bicep
#          parameters: 'appName=${{ env.AZURE_WEBAPP_NAME }}' 
          
   


      - name: Azure logout
        run: az logout
