name: Frontend-Deployment
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read
    
env:
  AZURE_RESOURCE_GROUP: xeniel
  AZURE_LOCATION: westeurope
  AZURE_MANAGED_BY: "moim.hossain@microsoft.com"

jobs:
  build-frontend-image:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      - uses: tenhaus/get-release-or-tag@v2
        id: tag      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false
      - name: Building container images
        run: ${PWD}/CognitiveDemo/build-frontend.sh $ImageTag $RegistryName
        env:
          ImageTag: ${{ steps.tag.outputs.tag }}
          RegistryName: "xenielscontainerregistry.azurecr.io"
      - name: Azure logout
        run: az logout
  deploy-frontend-images:
    runs-on: ubuntu-latest
    needs: build-frontend-image
    steps:      
      - uses: actions/checkout@v2
      - uses: tenhaus/get-release-or-tag@v2
        id: tag      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false
      - name: Prepare Revisions
        run: ${PWD}/Infrastructure/prepare-revisions.sh $ImageTag $FileName
        env:
          ImageTag: ${{ steps.tag.outputs.tag }}
          FileName: "frontend.bicep"

      - name: Deploy Bicep Template
        uses: Azure/arm-deploy@main
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./Infrastructure/frontend.bicep
          parameters: 'tagName=${{ steps.tag.outputs.tag }}'          
      - name: Azure logout
        run: az logout

  healthcheck:
    runs-on: ubuntu-latest
    needs: deploy-frontend-images
    outputs:
      status_code: ${{ steps.healthcheckStep.outputs.status_code }}      
    steps:      
      - uses: actions/checkout@v2
      - uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: Check Health API
        id: healthcheckStep
        run: ${PWD}/Infrastructure/health-check.sh $ImageTag
        env:
          ImageTag: ${{ steps.tag.outputs.tag }}

  triffic-load-50-percent:
    runs-on: ubuntu-latest
    needs: healthcheck
    steps:      
      - uses: actions/checkout@v2
      - run: echo "STATS CODE =====================================> ${{needs.healthcheck.outputs.status_code}}"
      - uses: tenhaus/get-release-or-tag@v2
        id: tag      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false
      - name: Prepare Revisions
        run: ${PWD}/Infrastructure/prepare-revisions.sh $ImageTag $FileName
        env:
          ImageTag: ${{ steps.tag.outputs.tag }}
          FileName: "frontend50.bicep"

      - name: Deploy Bicep Template
        uses: Azure/arm-deploy@main
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./Infrastructure/frontend50.bicep
          parameters: 'tagName=${{ steps.tag.outputs.tag }}'          
      - name: Azure logout
        run: az logout
  triffic-load-100-percent:
    runs-on: ubuntu-latest
    needs: triffic-load-50-percent
    steps:      
      - uses: actions/checkout@v2
      - uses: tenhaus/get-release-or-tag@v2
        id: tag      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false
      - name: Prepare Revisions
        run: ${PWD}/Infrastructure/prepare-revisions.sh $ImageTag $FileName
        env:
          ImageTag: ${{ steps.tag.outputs.tag }}
          FileName: "frontend100.bicep"

      - name: Deploy Bicep Template
        uses: Azure/arm-deploy@main
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./Infrastructure/frontend100.bicep
          parameters: 'tagName=${{ steps.tag.outputs.tag }}'          
      - name: Azure logout
        run: az logout 
  deactivate-older-revision:
    runs-on: ubuntu-latest
    needs: triffic-load-100-percent
    steps:      
      - uses: actions/checkout@v2
      - uses: tenhaus/get-release-or-tag@v2
        id: tag      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false
      - name: Deactivate old Revisions
        run: ${PWD}/Infrastructure/deactivate-prev-revision.sh
      - name: Azure logout
        run: az logout